# Implementación de un algoritmo evolutivo para resolver el problema del sudoku


El primer paso consiste en leer la matriz de 9x9 de un archivo .csv

In [1]:
import pandas
sudoku = pandas.read_csv('sudoku.csv',header=None).values
print(sudoku)

[[9 6 0 1 0 4 0 5 8]
 [0 7 8 3 2 5 6 0 9]
 [2 5 0 6 0 0 7 0 1]
 [8 0 1 4 0 7 5 0 6]
 [0 9 6 0 0 2 3 0 7]
 [7 0 5 9 6 1 0 2 4]
 [5 0 0 7 1 0 4 6 2]
 [3 1 7 2 0 6 9 0 0]
 [0 4 0 5 0 8 0 7 3]]


El siguiente paso consiste en calcular los números faltantes en cada renglón

In [2]:
import numpy as np
nums = np.arange(10) # Arreglo con los números del 0 al 9
print(nums)
print(sudoku[0])

[0 1 2 3 4 5 6 7 8 9]
[9 6 0 1 0 4 0 5 8]


In [3]:
nums = set(nums)     # Convertir a set
sr = set(sudoku[0])  # Convertir a set
missing_nums= nums.difference(sr) # Diferencia de conjuntos
print(missing_nums)

{2, 3, 7}


In [4]:
# Calcular los números faltantes en cada uno de los renglones
nums = set(np.arange(10))
missing_nums = []
for i in range(9):
    sr = set(sudoku[i])
    missing_nums.append( list(nums.difference(sr)) )
print(missing_nums)

[[2, 3, 7], [1, 4], [8, 9, 3, 4], [9, 2, 3], [8, 1, 4, 5], [8, 3], [8, 9, 3], [8, 4, 5], [1, 2, 6, 9]]


### Creación aleatoria de invidiuos 
Cada individuo se genera como una permutación aleatoria de los números faltantes

In [5]:
ind = []
for mn in missing_nums:
    mnind = np.copy(mn)
    np.random.shuffle(mnind) 
    ind.append(mnind)
print(ind)

[array([3, 7, 2]), array([1, 4]), array([9, 4, 8, 3]), array([2, 9, 3]), array([4, 1, 8, 5]), array([8, 3]), array([9, 3, 8]), array([5, 8, 4]), array([9, 2, 1, 6])]


In [6]:
def create_new_individual(missing_nums):
    ind = []
    for mn in missing_nums:
        mnind = np.copy(mn)
        np.random.shuffle(mnind)
        ind.append(mnind)
    return ind
ind = create_new_individual(missing_nums)
print(ind)

[array([7, 3, 2]), array([1, 4]), array([9, 8, 3, 4]), array([3, 2, 9]), array([4, 8, 1, 5]), array([8, 3]), array([9, 8, 3]), array([5, 8, 4]), array([9, 6, 1, 2])]


In [7]:
# Crear una copia de la matriz sudoku para crear una matriz del individuo
mind = np.copy(sudoku)
print(mind[0,:])
print(mind[0,:]==0) # Las casillas que son 0 en el primer renglón

[9 6 0 1 0 4 0 5 8]
[False False  True False  True False  True False False]


In [8]:
mind = np.copy(sudoku)
idx = mind[0,:]==0
mind[0,idx] = ind[0] # Remplazar los 0's con los valores del individuo
print('ind')
print(ind[0])
print('mind')
print(mind)

ind
[7 3 2]
mind
[[9 6 7 1 3 4 2 5 8]
 [0 7 8 3 2 5 6 0 9]
 [2 5 0 6 0 0 7 0 1]
 [8 0 1 4 0 7 5 0 6]
 [0 9 6 0 0 2 3 0 7]
 [7 0 5 9 6 1 0 2 4]
 [5 0 0 7 1 0 4 6 2]
 [3 1 7 2 0 6 9 0 0]
 [0 4 0 5 0 8 0 7 3]]


In [9]:
# Calcular la matriz del sudoku poniendo los valores del individuo
def calculate_individual_matrix(ind):
    mind = np.copy(sudoku)
    for i in range(9):
        idx = sudoku[i, :]==0
        mind[i, idx] = ind[i]
    return mind
ind = create_new_individual(missing_nums)
mind = calculate_individual_matrix(ind)
print('sudoku')
print(sudoku)
print('ind')
print(ind)
print('mind')
print(mind)

sudoku
[[9 6 0 1 0 4 0 5 8]
 [0 7 8 3 2 5 6 0 9]
 [2 5 0 6 0 0 7 0 1]
 [8 0 1 4 0 7 5 0 6]
 [0 9 6 0 0 2 3 0 7]
 [7 0 5 9 6 1 0 2 4]
 [5 0 0 7 1 0 4 6 2]
 [3 1 7 2 0 6 9 0 0]
 [0 4 0 5 0 8 0 7 3]]
ind
[array([7, 3, 2]), array([4, 1]), array([8, 3, 4, 9]), array([9, 2, 3]), array([5, 8, 4, 1]), array([8, 3]), array([3, 9, 8]), array([5, 4, 8]), array([2, 6, 1, 9])]
mind
[[9 6 7 1 3 4 2 5 8]
 [4 7 8 3 2 5 6 1 9]
 [2 5 8 6 3 4 7 9 1]
 [8 9 1 4 2 7 5 3 6]
 [5 9 6 8 4 2 3 1 7]
 [7 8 5 9 6 1 3 2 4]
 [5 3 9 7 1 8 4 6 2]
 [3 1 7 2 5 6 9 4 8]
 [2 4 6 5 1 8 9 7 3]]


In [10]:
def print_individual(ind):
    mind = calculate_individual_matrix(ind)
    s = ''
    for i in range(9):
        for j in range(9):
            s+= '|'+str(mind[i,j]) if j%3==0 else ' '+str(mind[i,j])
        s += '\n'
        if (i+1)%3==0 and i<8:
            s+= '------------------\n'
    print(s)
ind = create_new_individual(missing_nums)
print_individual(ind)

|9 6 3|1 2 4|7 5 8
|1 7 8|3 2 5|6 4 9
|2 5 3|6 9 4|7 8 1
------------------
|8 3 1|4 2 7|5 9 6
|8 9 6|4 5 2|3 1 7
|7 8 5|9 6 1|3 2 4
------------------
|5 3 9|7 1 8|4 6 2
|3 1 7|2 5 6|9 4 8
|9 4 2|5 6 8|1 7 3



### Cálculo de la aptitud (fitness)
La aptitud de un individuo se calcula a partir del número de errores (números duplicados) en los cuadrantes y en las columnas. Las filas no se toman en cuenta porque por definición los individuos son representados como permutaciones de los números faltantes en las filas.

In [11]:
# Imprimir la lista de los números únicos del primer renglón
ind = create_new_individual(missing_nums)
mind = calculate_individual_matrix(ind)
print(mind)
print(np.unique(mind[:,0]))

[[9 6 2 1 3 4 7 5 8]
 [1 7 8 3 2 5 6 4 9]
 [2 5 8 6 3 9 7 4 1]
 [8 9 1 4 2 7 5 3 6]
 [5 9 6 1 8 2 3 4 7]
 [7 3 5 9 6 1 8 2 4]
 [5 9 3 7 1 8 4 6 2]
 [3 1 7 2 4 6 9 8 5]
 [2 4 6 5 1 8 9 7 3]]
[1 2 3 5 7 8 9]


In [12]:
# Calcular el número de valores que faltan, igual al número de valores que se repiten
9-len(np.unique(mind[:,0]))

2

In [13]:
# Errores en las columnas
fit = 0
for c in range(9):
    fit += 9-len(np.unique(mind[:,c]))
print(fit)

15


In [14]:
# Obtener un cuadrante de la matriz
print( mind )
r = 0
c = 0
print( mind [r*3:r*3+3,c*3:c*3+3] )

[[9 6 2 1 3 4 7 5 8]
 [1 7 8 3 2 5 6 4 9]
 [2 5 8 6 3 9 7 4 1]
 [8 9 1 4 2 7 5 3 6]
 [5 9 6 1 8 2 3 4 7]
 [7 3 5 9 6 1 8 2 4]
 [5 9 3 7 1 8 4 6 2]
 [3 1 7 2 4 6 9 8 5]
 [2 4 6 5 1 8 9 7 3]]
[[9 6 2]
 [1 7 8]
 [2 5 8]]


In [15]:
# Errores en los cuadrantes
fit = 0
for r in range(3):
    for c in range(3):
        nums = np.unique( np.reshape(mind[r*3:r*3+3,c*3:c*3+3],(9)) )
        fit += 9 - len(nums)
print(fit)

16


In [16]:
def calculate_individual_fitness(ind):
    fit = 0
    mind = calculate_individual_matrix(ind)
    for c in range(9):
        fit += 9-len(np.unique(mind[:,c]))
    for r in range(3):
        for c in range(3):
            nums = np.unique( np.reshape(mind[r*3:r*3+3,c*3:c*3+3],(9)) )
            fit += 9 - len(nums)
    return fit
fit = calculate_individual_fitness(ind)
print(fit)

31


### Reproducción
La reproducción tiene el objetivo de mezclar las características de dos padres. 
En este caso utilizaremos la metodología punto de cruza descrito en el aula virtual

In [17]:
p1 = create_new_individual(missing_nums)
p2 = create_new_individual(missing_nums)
print(p1)
print(p2)

[array([3, 2, 7]), array([1, 4]), array([4, 8, 3, 9]), array([3, 2, 9]), array([8, 5, 4, 1]), array([3, 8]), array([3, 8, 9]), array([8, 4, 5]), array([9, 1, 2, 6])]
[array([7, 3, 2]), array([4, 1]), array([3, 4, 8, 9]), array([2, 9, 3]), array([1, 4, 8, 5]), array([8, 3]), array([8, 9, 3]), array([8, 4, 5]), array([9, 6, 1, 2])]


In [18]:
# Punto de cruza aleatorio
c = np.random.randint(1, 8)
print(c)

3


In [19]:
def crossover(p1,p2):
    o = []
    c = np.random.randint(1, 8)
    for i in range(0,c):
        o.append( np.copy(p1[i]) )
    for i in range(c,9):
        o.append( np.copy(p2[i]) )
    return o
o = crossover(p1,p2)
print(o)

[array([3, 2, 7]), array([1, 4]), array([4, 8, 3, 9]), array([2, 9, 3]), array([1, 4, 8, 5]), array([8, 3]), array([8, 9, 3]), array([8, 4, 5]), array([9, 6, 1, 2])]


### Mutación
La mutación tiene el objetivo de variar un poco un individuo. En este caso lo que haremos es elegir al azar uno de los renglones del individuo, después, también de forma aleatoria, seleccionar dos números faltantes, y lo que se realizará es intercambiar sus posiciones

In [20]:
ind = create_new_individual(missing_nums)
r = np.random.randint(9)
n1 = np.random.randint(len(ind[r]))
n2 = np.random.randint(len(ind[r]))
print('ind',ind)
print('r:',r,'n1:',ind[r][n1],'n2:',ind[r][n2])

ind [array([7, 2, 3]), array([4, 1]), array([3, 4, 8, 9]), array([9, 2, 3]), array([5, 4, 8, 1]), array([8, 3]), array([9, 3, 8]), array([5, 8, 4]), array([1, 2, 6, 9])]
r: 1 n1: 4 n2: 1


In [21]:
def mutation(ind):
    r = np.random.randint(9)
    n1 = np.random.randint(len(ind[r]))
    n2 = np.random.randint(len(ind[r]))
    ind[r][n1], ind[r][n2] = ind[r][n2], ind[r][n1]
    print('r:',r,'n1:',ind[r][n1],'n2:',ind[r][n2])
    return ind
print(ind)
ind = mutation(ind)
print(ind)

[array([7, 2, 3]), array([4, 1]), array([3, 4, 8, 9]), array([9, 2, 3]), array([5, 4, 8, 1]), array([8, 3]), array([9, 3, 8]), array([5, 8, 4]), array([1, 2, 6, 9])]
r: 1 n1: 4 n2: 1
[array([7, 2, 3]), array([1, 4]), array([3, 4, 8, 9]), array([9, 2, 3]), array([5, 4, 8, 1]), array([8, 3]), array([9, 3, 8]), array([5, 8, 4]), array([1, 2, 6, 9])]


### Evolución
Finalmente, hay que unir todas las piezas de código 

In [22]:
# Parámetros
N = 100    # tamaño de la población
Pc = 0.7   # probabilidad de cruza
Pm = 0.3   # probabilidad de mutación
G = 1000   # número de generaciones

# Leer el archivo
sudoku = pandas.read_csv("sudoku.csv", header=None).values

# Proceso evolutivo
population = init_population(sudoku,N)
fitness = calculate_fitness(population)
ind_elite, fit_elite = elite(population,fitness)

g = 0
print('Generation:',g,' fitness:',fit_elite)
while fit_elite>0 and g<G:
    population = selection(population,fitness)
    population = crossover(population,Pc)
    population = mutation(population,Pm)
    fitness = calculate_fitness(population)
    population, fitness, ind_elite, fit_elite = elite(population,fitness,ind_elite,fit_elite)
    g+=1
    if g%10==0:
        print('Generation:',g,' fitness:',fit_elite)
print('Generation:',g,' fitness:',fit_elite)
print_individual(ind_elite)

NameError: name 'init_population' is not defined

init_population: Crea una población de N individuos aleatorios, population es una lista de individuos.

calculate_fitness: Calcula la aptitud (fitness) de todos los individuos en la población y regresa un arreglo con el fitness de todos los individuos

elite: Encuentra y guarda una copia del mejor individuo de la población. 
Si aún no hay ningún individuo elite (primera vez que se manda llamar), sólo regresa el individuo elite y su aptitud.
Si ya hay un individuo elite hace lo siguiente. Si el mejor individuo en la población actual es mejor que el individuo elite, entonces el individuo elite y su fitness son actualizados. En otro caso, el individuo elite reemplaza a un individuo, seleccionado de forma aleatoria, de la población. 

selection: Recibe como parámetro la población y el arreglo de aptitudes; y regresa una nueva población de individuos aptos. Cada individuo en la nueva población es seleccionado utilizando torneo binario, es decir, dos individuos de la población anterior son seleccionados de forma aleatoria y el mejor de los dos es seleccionado para formar parte de la nueva población. El tamaño de la población nueva es del mismo tamaño que la población anterior.

crossover: Recibe como parámetro la población de individuos seleccionados y la probabilidad de cruza; y regresa una nueva población de individuos hijos. Los individuos de la nueva población son creados uno por uno como sigue. Primero, se genera un número aleatorio del 0 al 1. Si el número es menor o igual a la probabilidad de cruza, entonces el individuo nuevo es producto de la cruza de dos individuos seleccionados al azar de la población de individuos seleccionados. Si el número no es menor o igual a Pc, entonces el nuevo individuo es una copia de un individuo seleccionado al azar. 

mutation: Recibe como parámetro la población de individuos y la probabilidad de mutación; y regresa una nueva población de individuos. Los individuos de la nueva población son mutados uno por uno como sigue. Primero, se genera un número aleatorio del 0 al 1. Si el número es menor o igual a la probabilidad de mutación, entonces el individuo es mutado, si no, el individuo no se modifica.